apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  namespace: voting-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
      - name: voting-app
        image: dockersamples/examplevotingapp_vote:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "redis.voting-project.svc.cluster.local"
